eureka:
  client:
    register-with-eureka: false # I will set it to false because I don't want to register this microserver or the API Gateway with Eureka. Otherwise, if you need it for some reason, you can also remove this property.
server:
  port: 8222
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # I will set it to false because I don't want to register this microserver or the API Gateway with Eureka. Otherwise, if you need it for some reason, you can also remove this property.
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**