server:
  port: 8888
spring:
  profiles:
    active: native  #Native this means that it will be or automatically use the 56:04 active the native active profile and then let's also give a name for our application let's call it config server
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations